removeIllegals: true
removeBooks: true
nameColorCheck: false
removeLore: false
removeOverstacked: false
revertEnchantmentsMax: false
revertEnchantmentsConflicting: false
checkShulkers: true
fixUnbreakable: false
revertFurnace: false
maxBooksInShulker: true
maxBooks: 5
dropBooks: false

eventBlockBreak: true
eventBlockPlace: true
eventVehicleDestroy: true
eventPlayerItemDrop: true
eventEntityPickupItem: true
eventEntityDeath: true
eventPlayerSwapHandItems: true
eventPlayerItemHeld: true
eventInventoryMoveItem: true
eventPlayerInteractEntity: true
eventHangingBreak: true
eventEntityDamageByEntity: true
eventInventoryClick: true
eventInventoryOpen: true
eventBlockDispense: true
