removeBooks: true
nameColorCheck: false
removeLore: false
removeOverstacked: false
revertEnchantmentsMax: false
revertEnchantmentsConflicting: false
checkShulkers: true
fixUnbreakable: false
revertFurnace: false
maxBooksInShulker: true
maxBooks: 5
dropBooks: false

removeIllegals: true
illegalBlocks:
  - BEDROCK
  - ENDER_PORTAL_FRAME
  - BARRIER
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - MOB_SPAWNER
  - MONSTER_EGG
  - COMMAND
  - COMMAND_CHAIN
  - COMMAND_MINECART
  - COMMAND_REPEATING

# Additional to the illegals fix. Only allows x items of a type in a shulker.
limitInShulkers: false
limitedInShulkers:
  BEDROCK: 64 # Maximum amount of an item in shulkers

eventBlockBreak: true
eventBlockPlace: true
eventVehicleDestroy: true
eventPlayerItemDrop: true
eventEntityPickupItem: true
eventEntityDeath: true
eventPlayerSwapHandItems: true
eventPlayerItemHeld: true
eventInventoryMoveItem: true
eventPlayerInteractEntity: true
eventHangingBreak: true
eventEntityDamageByEntity: true
eventInventoryClick: true
eventInventoryOpen: true
eventBlockDispense: true
