# This plugin uses XMaterial to support 1.12.2 and 1.13+.
# You can find all the materials here: https://github.com/CryptoMorin/XSeries/blob/master/src/main/java/com/cryptomorin/xseries/XMaterial.java

removeBooks: true
nameColorCheck: false
removeLore: false
removeOverstacked: false
revertEnchantmentsMax: false
revertEnchantmentsConflicting: false
checkShulkers: true
fixUnbreakable: false
revertFurnace: false
maxBooksInShulker: true
maxBooks: 5
dropBooks: false
inventoryOpenIgnoreEnderChest: false # Only enable if the inventory open event causes lag

removeIllegals: true
illegalBlocks:
  - BEDROCK
  - ENDER_PORTAL_FRAME
  - BARRIER
  - STRUCTURE_BLOCK
  - STRUCTURE_VOID
  - MOB_SPAWNER
  - MONSTER_EGG
  - COMMAND
  - COMMAND_CHAIN
  - COMMAND_MINECART
  - COMMAND_REPEATING

# Only allows x slots of a type in a shulker.
limitInShulkers: false
limitedInShulkers:
  BEDROCK: 1 # Maximum amount of item slots in shulkers for this type

forceAsciiDisplayName: true

eventBlockBreak: true
eventBlockPlace: true
eventVehicleDestroy: true
eventPlayerItemDrop: true
eventEntityPickupItem: true
eventEntityDeath: true
eventPlayerSwapHandItems: true
eventPlayerItemHeld: true
eventInventoryMoveItem: true
eventPlayerInteractEntity: true
eventHangingBreak: true
eventEntityDamageByEntity: true
eventInventoryClick: true
eventInventoryOpen: true
eventPlayerJoin: true
eventBlockDispense: true

armorMaterials:
  - CHAINMAIL_HELMET
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_LEGGINGS
  - CHAINMAIL_BOOTS
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - GOLD_HELMET
  - GOLD_CHESTPLATE
  - GOLD_LEGGINGS
  - GOLD_BOOTS
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS

weaponMaterials:
  - WOOD_AXE
  - STONE_AXE
  - IRON_AXE
  - GOLD_AXE
  - DIAMOND_AXE
  - WOOD_SWORD
  - STONE_SWORD
  - IRON_SWORD
  - GOLD_SWORD
  - DIAMOND_SWORD
  - BOW